### ISSUE TITLE
Crashes when opening from Finder

### ISSUE THREAD

**Issue by yorkxin** [francisfeng/everything-okjson#14] opened 2023-02-15 06:14 UTC
**Describe the bug**

OK JSON crashes when opening a JSON file from Finder

從 Finder 選擇用 OK JSON 打開 JSON 文件時，OK JSON 會崩潰。

**To Reproduce**
1. In Finder, right click on any JSON file
2. Choose Open With -> OK JSON from the menu (if not present, choose 'Others...' and select OK JSON app)
3. OK JSON app crashes

**Expected behavior**

OK JSON should open the JSON File I selected on Finder

**Screenshots**

N/A

**Desktop (please complete the following information):**
 - OS: macOS 13.2
 - Browser N/A
 - Version 1.9.0 (26)

**Smartphone (please complete the following information):**

**Additional context**

**Comment by francisfeng** [comment] 2023-03-14 06:29
Thanks for reporting. I’ve identified the cause. It took sometime to reproduce because it’s a weird issue that only happened to non-pro users.

It’s fixed in 2.0, which will probably come out in the next couple months.

**Closed by francisfeng** 2023-03-14 06:29 UTC
